name: 'eirctl-setup'
description: |
  Sets up eirctl binary. 

  Allows for version specification.

inputs:
  version: 
    description: Version of the binary to download.
    required: false 
    default: latest
  isPrerelease:
    description: Look for version in prerelease section
    required: false
    default: 'false'
  sha256:
    description: SHA-256 checksum of the binary.
    required: false

runs:
  using: node24
  main: task.js
