name: PR workflow

on:
  pull_request: 
    branches: 
      - main

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

jobs:
  actions-builder:
    name: Build and test all actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install PNPM 
        run: npm i -g pnpm@9.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Run Test
        run: |
          pnpm i
          pnpm run test
          pnpm run test:merge

      - name: Publish Junit style Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/.coverage/junit.xml'
      
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '.coverage/cobertura-coverage.xml'
          badge: true
          format: 'markdown'
          output: 'both'
          thresholds: '80 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md