name: PR workflow

on:
  pull_request: 
    branches: 
      - main

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

jobs:
  actions-builder:
    name: Build and test all actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: install PNPM 
        run: npm i -g pnpm@9.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Run Test
        run: |
          pnpm i
          pnpm run test
          pnpm run test:merge

      - name: Publish Junit style Test Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always() # always run even if the previous step fails
        with:
          name: junit-report
          path: '**/.coverage/junit.xml'
          if-no-files-found: warn
          retention-days: 7
      
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '.coverage/cobertura-coverage.xml'
          badge: true
          format: 'markdown'
          output: 'both'
          thresholds: '80 80'
