name: PR workflow

on:
  pull_request: 
    branches: 
      - main

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

jobs:
  actions-builder:
    name: Build and test all actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: install PNPM 
        run: npm i -g pnpm@12.6.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Check Actions integrity
        run: |
          pnpm i
          pnpm run build
          git status --porcelain --untracked-files=no
          if [ ! -z "$(git status --porcelain --untracked-files=no)" ]; then
            if [ ! -z ${CI+x} ] ; then
              echo "In CI with an unclean tree - exiting"
              echo "Info: make sure you have run pnpm run build locally and committed"
              exit 1
            fi
          fi

      - name: Run Test
        run: |
          pnpm run test
          pnpm run test:merge

      - name: Publish Junit style Test Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always() # always run even if the previous step fails
        with:
          name: junit-report
          path: '**/.coverage/junit.xml'
          if-no-files-found: warn
          retention-days: 7
      
      - name: Upload coverage report
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@d8e329117199404bba6fc81efe8093dc7c015e34 # v1.4.7
        with:
          file: '.coverage/cobertura-coverage.xml'
          language: js
          label: actions-coverage
