name: tester 

on:
  push: 
    branches:
    - main
    - feat/*

jobs:
  process-json: 
    runs-on: ubuntu-latest
    env: {}       
    outputs:
      complex2Level__key1__c2l_key1: ${{ steps.publishedJson.outputs.complex2Level__key1__c2l_key1 }}
    steps:
    - uses: actions/checkout@v4
    - uses: ensono/actions/tasks/process-json@v0.2.1
      id: publishedJson
      with: 
        separator: "__"
        jsonStringOrPath: process-json/.tests/sample-output.json
        isTerraformOutput: true
    - name: test within the job 
      run: |
        echo "complex2Level__key1__c2l_key1: ${{ steps.publishedJson.outputs.complex2Level__key1__c2l_key1 }}"
        echo "complex2Level_arr__key1__c2larr_key1: ${{ steps.publishedJson.outputs.complex2Level_arr__key1__c2larr_key1 }}"

  tascktl-setup:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        # - uses: ensono/actions/taskctl-setup@main
        - uses: ./taskctl-setup
          id: taskctlsetup
          with: 
            version: latest
            isPrerelease: true
        - run: |
            taskctl -v

  across-jobs:
    needs: 
      - process-json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: output across jobs
        run: |
          echo "complex2Level__key1__c2l_key1: ${{ needs.process-json.outputs.complex2Level__key1__c2l_key1 }}"